# Generated by Django 5.1.1 on 2024-09-21 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rpmsettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashfrom', models.IntegerField(blank=True, null=True)),
                ('cashtill', models.IntegerField(blank=True, null=True)),
                ('rpmfrom', models.FloatField(blank=True, null=True)),
                ('rpmtill', models.FloatField(blank=True, null=True)),
                ('cashdaily', models.IntegerField()),
                ('bonus', models.FloatField()),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.vehicles')),
            ],
        ),
    ]
