# Generated by Django 5.1.1 on 2024-09-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_dispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(help_text='Unit name', max_length=20, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('companyowned', models.BooleanField(default=True)),
                ('info', models.TextField(blank=True, help_text='Info', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='visit.vehicles')),
            ],
        ),
    ]
