# Generated by Django 5.1.1 on 2024-09-21 12:44

import django.db.models.deletion
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_trucks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(help_text='Loads No.', max_length=20, unique=True)),
                ('pickupstate', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('pickupzip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('droppstate', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('dropzip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('pickupdate', models.DateField()),
                ('pickuptime', models.TimeField()),
                ('dropdate', models.DateField()),
                ('droptime', models.TimeField()),
                ('allmiles', models.FloatField()),
                ('totalrate', models.FloatField()),
                ('rate', models.FloatField()),
                ('info', models.TextField(blank=True, help_text='Info', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visit.dispatch')),
                ('trtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visit.vehicles')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visit.trucks')),
            ],
        ),
    ]
