# Generated by Django 5.1.1 on 2024-09-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_loads'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIClusterResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.dispatch')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.trucks')),
            ],
        ),
    ]
